server:
  port: 8000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xiong-blog?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    open: false
    port: 6379
    host: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xjt.blog.entity

aliyun:
  oss:      #aliyun-oss信息已失效 AK SK 替换成自己的吧
    endPoint: oss-cn-shenzhen.aliyuncs.com
    urlPrefix: xiong-test-srt.oss-cn-shenzhen.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: xiong-test-srt
    fileHost: files