server:
  port: 8000
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.xjt: debug
    org.springframework: warn

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xiong-blog?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    open: false
    port: 6379
    host: 127.0.0.1
  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件大小
      max-request-size: 1000MB    # 设置总上传的文件大小
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:/mapper/*.xml   # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: com.xjt.blog.entity   #搜索指定包别名

aliyun:
  oss:      #aliyun-oss信息已失效 AK SK 替换成自己的吧
    endPoint: oss-cn-shenzhen.aliyuncs.com
    urlPrefix: xiong-test-srt.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tKyvQK5k1cA8AsHy7ay
    accessKeySecret: KHzCSoNGKLHOfzfYyu323ZmINKtwn2
    bucketName: xiong-test-srt
    fileHost: files

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

--- #---------------------聚合数据 （历史上的今天）---------------------------
juhe:
  todayOnhistory:
    key: b23a502397dcf997232395bd84e52c41

xiongblog:
  # 名称
  name: XiongBlog
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/xiongblog/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: Spec